---
- name: Configure servers & routers
  hosts: all
  become: true
  tasks:

    - name: Set up NAT on inetRouter
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { src: "templates/iptables_rules.ipv4", dest: "/etc/iptables_rules.ipv4", mode: "0644" }
        - { src: "templates/iptables_restore", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
      when: (ansible_hostname == "inetRouter")


    - name: Set up NAT on inetRouter2
      ansible.builtin.template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: root
        group: root
        mode: "{{ item.mode }}"
      with_items:
        - { src: "templates/iptables_rules.ipv4_intRouter2", dest: "/etc/iptables_rules.ipv4", mode: "0644" }
        - { src: "templates/iptables_restore", dest: "/etc/network/if-pre-up.d/iptables", mode: "0755" }
      when: (ansible_hostname == "inetRouter2")


    - name: Set up forward packages across routers
      ansible.posix.sysctl:
        name: net.ipv4.conf.all.forwarding
        value: '1'
        state: present
      when: "'routers' in group_names"

    - name: Disable default route
      ansible.builtin.copy:
        src: "templates/00-installer-config.yaml"
        dest: "/etc/netplan/00-installer-config.yaml"
        owner: root
        group: root
        mode: 0644
      when: (ansible_hostname != "inetRouter")

    - name: Add default gateway for centralRouter
      ansible.builtin.template:
        src: "templates/50-vagrant_{{ansible_hostname}}.yaml"
        dest: /etc/netplan/50-vagrant.yaml
        owner: root
        group: root
        mode: 0644

    - name: Install nginx
      ansible.builtin.apt:
        name: nginx
        update_cache: true
      when: (ansible_hostname == "centralServer")
    
    - name: Install nginx
      ansible.builtin.apt:
        name: nmap
        update_cache: true
      when: (ansible_hostname == "centralRouter")

    - name: Start nginx
      # Comment
      ansible.builtin.systemd_service:
        enabled: true
        name: nginx
        state: started
      when: (ansible_hostname == "centralServer")

    - name: Copy knock to centralRouter
      ansible.builtin.copy:
          dest: /home/vagrant/
          mode: "0755"
          owner: vagrant
          src: "knock.sh"
      when: (ansible_hostname == "centralServer")

    - name: Restart all hosts
      ansible.builtin.reboot:
        reboot_timeout: 600
